services:
  app:
    build:
      target: development
    expose:
      - '5173'
    command: ./docker/init-dev.sh
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      WEBSITE_DOMAIN: ${WEBSITE_DOMAIN}
      INTERNAL_CLIENT_URL: 'http://app:5173'
      VITE_API_URL: 'https://${WEBSITE_DOMAIN}'
      DEBUG: 'app:*'
    healthcheck:
      test:
        [
          'CMD',
          '/bin/sh',
          './docker/app-health-check.sh',
          'http://0.0.0.0:3000/ping',
          'http://0.0.0.0:5173',
        ]
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  db:
    ports:
      - '5433:5432'
    environment:
      - TEST_DB_NAME=${DB_NAME}_cypress
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    networks:
      - internal_network
    ports:
      - '1025:1025'
      - '8025:8025'

  nginx:
    image: nginx:alpine
    command: /docker/init-nginx.sh
    environment:
      VITE_PORT: 5173
      NODE_ENV: development
    networks:
      - web
      - internal_network
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.http.services.my-nginx-dev.loadbalancer.server.port=80'
      - 'traefik.http.routers.app-dev.rule=Host(`${WEBSITE_DOMAIN}`)'
      - 'traefik.http.routers.app-dev.entrypoints=websecure'
      - 'traefik.http.routers.app-dev.tls=true'
    volumes:
      - ./docker:/docker
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/includes:/etc/nginx/includes
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./client/dist:/usr/share/nginx/html:ro
      - system_status:/app/docker/system_status
