services: 
  app:
    build: 
      context: .
      target: development
      args:
        DOCKER_BUILDKIT: 1
    volumes: 
      - .:/app
      - /app/node_modules
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: '3'
    expose:
      - "${API_PORT}"
      - "${VITE_PORT}"
    environment:
      CLIENT_DOMAIN: "localhost"
      INTERNAL_CLIENT_URL: "http://app:${VITE_PORT}"  
      VITE_API_URL: "http://localhost"
      VITE_HOST: ${VITE_HOST:-0.0.0.0}
      API_HOST: ${API_HOST:-0.0.0.0}
      NODE_ENV: development
      PORT: ${API_PORT}
      # DB
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db 
      # AUTH
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      # OUTPUT
      DEBUG: "app:*"
    depends_on: 
      db:
        condition: service_healthy    
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -v -f http://0.0.0.0:${API_PORT}/ping && curl -v -f http://0.0.0.0:${VITE_PORT} || echo 'Health check failed with status $?'"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    command: ./docker/init-app.sh
    networks: 
      - app_network    

  db: 
    image: postgres:latest
    networks: 
      - app_network    
    ports: 
      - "5433:5432"
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TEST_DB_NAME=${DB_NAME}_cypress
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mailhog: 
    image: mailhog/mailhog:latest
    container_name: mailhog
    networks: 
      - app_network    
    ports:
      - "1025:1025"
      - "8025:8025"

  nginx:
    environment: 
      VITE_PORT: ${VITE_PORT}


networks: 
  app_network:
    driver: bridge


volumes: 
  postgres_data: 
