services: 
  app:
    environment:
      NODE_ENV: test
      VITE_API_URL: http://app:3000

  cypress: 
    build:
      context: .
      dockerfile: Dockerfile.cypress
      args: 
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
 
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    environment: 
      - CYPRESS_baseUrl=http://app:5173
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - TEST_DB_NAME=${TEST_DB_NAME}
      - NODE_ENV=test
      - IN_DOCKER=true
      - CYPRESS_QUIET=1
      - FORCE_COLOR=1
      - DEBUG=cypress:server:browsers:*
      - DEBUG=cypress:user:log
      - NODE_DEBUG=console
      - VITE_API_URL=http://app:3000
    volumes: 
      - .:/e2e:ro
      - ./cypress:/e2e/cypress
      - ./cypress.config.cjs:/e2e/cypress.config.cjs
      - ./cypress/videos:/e2e/cypress/videos

    working_dir: /e2e
    
    command: npx cypress run --config-file cypress.config.cjs --browser chrome --headless

volumes: 
  postgres_data: 
