services:
  traefik:
    image: traefik:v3.0
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    networks:
      - web
      - internal_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'ping', '-c', '1', '${WEBSITE_DOMAIN}']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  nginx:
    depends_on:
      traefik:
        condition: service_healthy

networks:
  web:
    driver: bridge
