x-test-app-defaults: &test-app-defaults 
  INTERNAL_CLIENT_URL: "http://nginx:80"
  CLIENT_DOMAIN: 'localhost'
  VITE_API_URL: "http://nginx:80"
  NODE_ENV: test

services: 
  app:
    environment:
      <<: *test-app-defaults

  cypress: 
    build:
      context: .
      dockerfile: Dockerfile.cypress
      args: 
        DOCKER_BUILDKIT: 1
 
    depends_on:
      nginx: 
        condition: service_healthy
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    environment: 
      <<: *test-app-defaults
      # DB
      DB_USER: ${DB_USER}
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      TEST_DB_NAME: ${TEST_DB_NAME}
      # OUTPUT
      # CYPRESS_QUIET: 1
      FORCE_COLOR: 1
      DEBUG: cypress:user:log
      NODE_DEBUG: console
    volumes: 
      # Read-only source files
      - ./tsconfig.json:/e2e/tsconfig.json:ro
      - ./cypress/tsconfig.json:/e2e/cypress/tsconfig.json:ro
      - ./cypress/e2e:/e2e/cypress/e2e:ro
      - ./cypress/support:/e2e/cypress/support:ro
      - ./cypress/fixtures:/e2e/cypress/fixtures:ro
      - ./cypress/plugins:/e2e/cypress/plugins:ro
      - ./cypress.config.cjs:/e2e/cypress.config.cjs:ro
      
      # Writable output directories
      - ./cypress/videos:/e2e/cypress/videos
      - ./cypress/screenshots:/e2e/cypress/screenshots
      - ./cypress/downloads:/e2e/cypress/downloads  
      
    working_dir: /e2e
    
    command: bun run test:docker

  nginx:
    environment: 
      AUTH_RATE: "1000r/m"
      VERIFY_RATE: "500r/m"
      
volumes:  
  postgres_data: 
