x-test-app-defaults: &test-app-defaults
  NODE_ENV: test
  WEBSITE_DOMAIN: 'localhost'
  INTERNAL_CLIENT_URL: 'http://nginx:80'
  VITE_API_URL: 'http://nginx:80'
  DB_NAME: ${DB_NAME}
  TEST_DB_NAME: ${DB_NAME}_cypress
  EMAIL_SERVICE_SYSTEM_EMAIL_ADDRESS: ${EMAIL_SERVICE_SYSTEM_EMAIL_ADDRESS}
  EMAIL_SERVICE_SYSTEM_EMAIL_SENDER: ${EMAIL_SERVICE_SYSTEM_EMAIL_SENDER}
  VITE_EMAIL_ADDRESS_SUPPORT: ${VITE_EMAIL_ADDRESS_SUPPORT:-support@${WEBSITE_DOMAIN:-localhost}}

services:
  app:
    environment:
      <<: *test-app-defaults
      SUPER_ADMIN_EMAIL: 'superadmin@local.dev'

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
      args:
        DOCKER_BUILDKIT: 1
    networks:
      - 'app_network'

    depends_on:
      nginx:
        condition: service_healthy
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      <<: *test-app-defaults
      # DB
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # OUTPUT
      FORCE_COLOR: 1
      DEBUG: cypress:user:log
      NODE_DEBUG: console
      CYPRESS_CHROME_FLAGS: '--disable-dev-shm-usage --no-sandbox'
    volumes:
      # Read-only source files
      - ./tsconfig.json:/e2e/tsconfig.json:ro
      - ./docker/cypress-run.sh:/e2e/docker/cypress-run.sh:ro
      - ./cypress.config.ts:/e2e/cypress.config.ts:ro
      - ./cypress:/e2e/cypress:ro
      - system_status:/app/docker/system_status

      # Writable output directories
      - type: bind
        source: ./cypress/videos
        target: /e2e/cypress/videos
        consistency: delegated
      - type: bind
        source: ./cypress/screenshots
        target: /e2e/cypress/screenshots
        consistency: delegated
      - type: bind
        source: ./cypress/downloads
        target: /e2e/cypress/downloads
        consistency: delegated

    working_dir: /e2e

    command: ./docker/cypress-run.sh

    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  nginx:
    environment:
      AUTH_RATE: '1000r/m'
      VERIFY_RATE: '500r/m'

  mailhog:
    command: []
