const fifteenMinutes = 15 * 60 * 1000;
const sevenDays = 7 * 24 * 60 * 60 * 1000;

const isTestEnv = process.env.NODE_ENV === 'test';

const ACCESS_TOKEN_EXPIRY_TEST = '5s';
const ACCESS_TOKEN_EXPIRY_APP = '15m';
const ACCESS_COOKIE_EXPIRY_TEST = 5 * 1000; 
const ACCESS_COOKIE_EXPIRY_APP = fifteenMinutes;
export const ACCESS_TOKEN_EXPIRY = isTestEnv ? ACCESS_TOKEN_EXPIRY_TEST : ACCESS_TOKEN_EXPIRY_APP;
export const ACCESS_COOKIE_EXPIRY = isTestEnv ? ACCESS_COOKIE_EXPIRY_TEST : ACCESS_COOKIE_EXPIRY_APP;

const REFRESH_TOKEN_EXPIRY_TEST = '9s';
const REFRESH_TOKEN_EXPIRY_APP = '7d';
const REFRESH_COOKIE_EXPIRY_TEST = 9 * 1000; 
const REFRESH_COOKIE_EXPIRY_APP = sevenDays;
export const REFRESH_TOKEN_EXPIRY = isTestEnv ? REFRESH_TOKEN_EXPIRY_TEST : REFRESH_TOKEN_EXPIRY_APP;
export const REFRESH_COOKIE_EXPIRY = isTestEnv ? REFRESH_COOKIE_EXPIRY_TEST : REFRESH_COOKIE_EXPIRY_APP;

const VERIFICATION_TOKEN_EXPIRY_TEST = '15 seconds';
const VERIFICATION_TOKEN_EXPIRY_APP = '20 minutes';
export const VERIFICATION_TOKEN_EXPIRY = isTestEnv ? VERIFICATION_TOKEN_EXPIRY_TEST : VERIFICATION_TOKEN_EXPIRY_APP;
