tls:
  certificates:
    - certFile: '/etc/traefik/certs/local/localhost.pem'
      keyFile: '/etc/traefik/certs/local/localhost-key.pem'

  options:
    default-tls-options:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
