-- UP
ALTER TABLE members
ADD COLUMN verified BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS verification_tokens (
  token VARCHAR(255) PRIMARY KEY,
  user_id INTEGER NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP + INTERVAL '24 hours'),
  FOREIGN KEY (user_id) REFERENCES members(id) ON DELETE CASCADE
);

-- DOWN
DROP TABLE IF EXISTS verification_tokens;

ALTER TABLE members DROP COLUMN IF EXISTS verified;
