-- UP
CREATE TABLE IF NOT EXISTS reset_password_tokens (
  token VARCHAR(255) PRIMARY KEY,
  user_id UUID NOT NULL,
  email VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP + INTERVAL '20 minutes'),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE 
)

-- DOWN 
DROP TABLE IF EXISTS reset_password_tokens;
