name: Cypress Tests

on: 
  push: 
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  cypress-tests:
    runs-on: ubuntu-latest

    env: 
      DB_NAME: ci_db
      TEST_DB_NAME: ci_db_cypress
      DB_USER: postgres
      DB_PASSWORD: password1
      AUTH_TOKEN_SECRET: test-secret
      REFRESH_TOKEN_SECRET: test-refresh-secret

    steps: 
      - uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get install -y make

      - name: Build test containers
        run: make build-tests

      - name: Run tests
        run: make tests

      - name: Upload test artifacts 
        if: always()
        uses: actions/upload-artifact@v3
        with: 
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots

      - name: Cleanup
        if: always()
        run: make clean-tests
