name: Cypress Tests

on: 
  push: 
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  cypress-tests:
    runs-on: ubuntu-latest

    env: 
      DB_NAME: ci_db
      TEST_DB_NAME: ci_db_cypress
      DB_USER: postgres
      DB_PASSWORD: password1
      AUTH_TOKEN_SECRET: test-secret
      REFRESH_TOKEN_SECRET: test-refresh-secret
      VITE_PORT: 5173
      VITE_EMAIL_ADDRESS_SUPPORT: 'test@support.com'

    steps: 
      - uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get install -y make

      - name: Prepare artifact directories
        run: |
          mkdir -p cypress/screenshots cypress/videos cypress/downloads
          chmod -R 777 cypress/screenshots cypress/videos cypress/downloads

      - name: Check for artifacts Before Tests
        run: |
          echo "Checking for artifacts..."
          ls -la cypress || true


      - name: Build test containers
        run: make build-tests
  
      - name: Run tests
        run: make run-tests
        id: run_tests
        continue-on-error: false

      - name: Check for artifacts
        if: failure()
        run: |
          echo "Checking for artifacts..."
          ls -la cypress/screenshots || true
          ls -la cypress/videos || true

      - name: Upload test artifacts 
        if: failure()
        uses: actions/upload-artifact@v4
        with: 
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
          if-no-files-found: warn

      - name: Cleanup
        if: always()
        run: make clean-tests
