name: Cypress Tests

on: 
  push: 
    # comment
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened]

jobs: 
  cypress-tests:
    runs-on: ubuntu-latest

    env: 
      API_PORT: 3000
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: password1  
      POSTGRES_DB: testdb        
      DB_NAME: testdb
      TEST_DB_NAME: testdbname
      DB_USER: postgres
      DB_PASSWORD: password1
      AUTH_TOKEN_SECRET: test-secret
      REFRESH_TOKEN_SECRET: test-refresh-secret
      VITE_PORT: 4173

    steps: 
      - uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get install -y make

      - name: Clean environment
        run: make clean

      - name: Build test containers
        run: make build-tests

      - name: Run tests
        run: make tests

      - name: Upload test artifacts 
        if: always()
        uses: actions/upload-artifact@v3
        with: 
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots

      - name: Cleanup
        if: always()
        run: make clean
